#
# Module manifest for module 'NabuNetManager'
#
# Generated by: Atkelar
#
# Generated on: 8/20/2023
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule           = 'NabuNetManager.psm1'

    # Version number of this module.
    ModuleVersion        = '0.0.11'

    # Supported PSEditions
    CompatiblePSEditions = @("core")

    # ID used to uniquely identify this module
    GUID                 = '96a3af03-c235-4d5b-81ee-0dd91b86beac'

    # Author of this module
    Author               = 'Atkelar'

    # Company or vendor of this module
    CompanyName          = 'Atkelar'

    # Copyright statement for this module
    Copyright            = '(c) 2023-2024 by Atkelar. All rights reserved.'

    # Description of the functionality provided by this module
    Description          = 'This is a powershell script module to wrap access to the REST endpoints of the NabuNet retro computing service; Curently a pure beta and "try something new" release. See the project website on GitHub for details and updates!'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion    = '7.0'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess     = @("NabuNet.format.ps1xml")

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules = @("Microsoft.PowerShell.Archive")

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport    = @("Register-Host", "Get-Host", "Connect-Host", 
        "Get-Account", "Get-ServerAnnouncement", "Set-ServerAnnouncement", "Clear-ServerAnnouncement",
        "Get-MailTemplate", "Set-MailTemplate", "Approve-Account", "Get-UpdateImages", "Clear-FirmwareImage", "Clear-ConfigImage", "Set-FirmwareImage", "Set-ConfigImage", 
        "Build-Asset", "Build-FirmwareAsset", "Build-ConfigAsset", "Get-AccountSecurity", "Test-Mailing")

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport      = @()

    # Variables to export from this module: don't. We use variables internally for the "session" and tokens
    VariablesToExport    = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport      = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData          = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags         = @("Nabu", "Retro")

            # A URL to the license for this module.
            # LicenseUri = 'https://'

            # A URL to the main website for this project.
            ProjectUri   = 'https://github.com/Atkelar/nabunet'

            # A URL to an icon representing this module.
            IconUri      = 'https://raw.githubusercontent.com/Atkelar/nabunet/main/Assets/nabunet_logo.png'

            # ReleaseNotes of this module
            ReleaseNotes = 'This module contains accessor wrappers for talking with the NabuNet server software. See project website for more details!'

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    DefaultCommandPrefix = 'NabuNet'
}

